[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/*.(js|css|json|webp|svg|ttf|woff|woff2)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[dev]
  port = 3000
  publish = "dist"
  command = "npm run dev"
  targetPort = 5173

[context.production]
  command = "npm run build"
  publish = "dist"
